version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "22:00"
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: react-scripts
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.3
    - 11.2.4
    - 11.2.5
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: handlebars
    versions:
    - 4.7.6
